### ISSUE TITLE
Error trying to run: "Unrecognized tag: init-widgets"

### ISSUE THREAD

**Issue by davidgilbertson** [patrick-steele-idem/marko-vs-react#4]
I cloned the repo, `npm i` (no errors), `npm test` and got an error. It's the same error for `npm start`.

I see a reference to `<init-widgets/>` in `page.marko` but nowhere else. The [error page](https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag) suggests it needs to be in `package.json`, so I tried `npm i init-widgets` but it doesn't exist.

Any ideas? (I know nothing at all about Marko)

```
LM-SYD-00000:marko-vs-react dgilbertson$ npm start

> marko-vs-react@1.0.0 start /Users/dgilbertson/www/marko-vs-react
> node server.js

/Users/dgilbertson/www/marko-vs-react/node_modules/marko/compiler/Compiler.js:84
        throw error;
        ^

Error: An error occurred while trying to compile template at path "/Users/dgilbertson/www/marko-vs-react/benchmark-client/page.marko". Error(s) in template:
1) [benchmark-client/page.marko:21:8] Unrecognized tag: init-widgets - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag

    at handleErrors (/Users/dgilbertson/www/marko-vs-react/node_modules/marko/compiler/Compiler.js:82:21)
    at Compiler.compile (/Users/dgilbertson/www/marko-vs-react/node_modules/marko/compiler/Compiler.js:151:9)
    at _compile (/Users/dgilbertson/www/marko-vs-react/node_modules/marko/compiler/index.js:89:33)
    at Object.compile (/Users/dgilbertson/www/marko-vs-react/node_modules/marko/compiler/index.js:103:12)
    at compile (/Users/dgilbertson/www/marko-vs-react/node_modules/marko/node-require.js:52:38)
    at Object.markoRequireExtension [as .marko] (/Users/dgilbertson/www/marko-vs-react/node_modules/marko/node-require.js:120:27)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

**Comment by patrick-steele-idem** [comment]
Hey @davidgilbertson, thanks for checking out the repo. It's been superseded by the following repo that is actively maintained to use latest versions of UI libraries: https://github.com/marko-js/isomorphic-ui-benchmarks

I'll update the README to make this clear. Thank you for opening the issue!

With `isomorphic-ui-benchmarks` we added more UI libraries to the mix (including Inferno, Preact, and Vue) and we also improved how the benchmarks are executed.

**Comment by davidgilbertson** [comment]
Now that's a quick reply! I'll check it out now. Much better results for Marko in the new repo. Interesting.

**Comment by patrick-steele-idem** [comment]
The old repo measured performance by starting a server and benchmarking the server by making a lot of HTTP requests. This introduced a lot of variance that made the results less consistent (maybe due to OS, network layer, etc.) and it introduced more variables. The new benchmark just measures the time it takes to render the HTML string that would be sent down to the browser. With that said, Marko v4 has gotten a lot faster over time so the results on `marko-vs-react` no longer reflect the latest performance. Let me know if you have any questions about the new benchmark.
